<?php
// $Id$

/**
 * Implementation of hook_perm().
 */
//onModuleCreationWizard
function aset_perm() {
    return array(
        'access penata content',
		'access laporan penata'
	);
}

/**
 * Implementation of hook_menu().
 */

function aset_menu() {

	$items['aset'] = array (
      'title' => 'Antrian Jurnal Aset',
	  'description' => 'Antrian Jurnal Aset',
	  'title callback' => 'aset_title_callback',	  
      'page callback' => 'aset_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'aset_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
	$items['aset/jurnal'] = array (
      'title' => 'Jurnal Aset',
	  'description' => 'Jurnal Aset',
	  'title callback' => 'aset_title_callback',	  
      'page callback' => 'aset_edit_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'aset_edit_main.php',
      'type' => MENU_NORMAL_ITEM,
    );

	

    return $items;
}


function aset_title_callback() {
    return t('Jurnal Aset');
}


