<?php
// $Id$

/**
 * Implementation of hook_perm().
 */
//onModuleCreationWizard
function manageuser_perm() {
    return array(
        'access penata content',
		'access laporan penata'
	);
}

/**
 * Implementation of hook_menu().
 */

function manageuser_menu() {

	$items['manageuser'] = array (
      'title' => 'Antrian Manageuser',
	  'description' => 'Antrian Jurnal manageuser',
	  'title callback' => 'manageuser_title_callback',	  
      'page callback' => 'manageuser_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'manageuser_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
	$items['manageuseredit'] = array (
      'title' => 'Antrian Manageuser',
	  'description' => 'Antrian Jurnal manageuser',
	  'title callback' => 'manageuseredit_title_callback',	  
      'page callback' => 'manageuseredit_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'manageuseredit_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
	
	

    return $items;
}


function manageuser_title_callback() {
    return t('Antrian Jurnal manageuser');
}

function manageuseredit_title_callback() {
	return t('Jurnal Kas manageuser');
}

