<?php
// $Id$

/**
 * Implementation of hook_perm().
 */
//onModuleCreationWizard
function pendapatanlap_perm() {
    return array(
        'access pendapatan content',
		'access laporan pendapatan'
	);
}

/** 
 * Implementation of hook_menu().
 */

function pendapatanlap_menu() {


	$items['pendapatanlap'] = array (
      'title' => 'Pendapatan per SKPD',
	  'description' => 'Pendapatan per SKPD',
	  //'title callback' => 'pendapatanlap_title_callback',	  
      'page callback' => 'pendapatanlap_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'pendapatanlap_main.php',
      'type' => MENU_NORMAL_ITEM,
    );

	$items['pendapatanrek'] = array (
      'title' => 'Pendapatan per Rekening',
	  'description' => 'Pendapatan per Rekening',
	  //'title callback' => 'pendapatanrek_title_callback',	  
      'page callback' => 'pendapatanrek_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'file' => 'pendapatanrek_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
	$items['pendapatanrek/skpd'] = array (
      'title' => 'Pendapatan SKPD',
	  'description' => 'Pendapatan SKPD',
	  //'title callback' => 'pendapatanrekskpd_title_callback',	  
      'page callback' => 'pendapatanrek_skpd_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'file' => 'pendapatanrek_skpd_main.php',
      'type' => MENU_NORMAL_ITEM,
    );	

	$items['pendapatanlap/chart'] = array (
	  'title' => 'Analisis Pendapatan',
      'page callback' => 'pendapatanlap_chart_main',
      'page arguments' => array('pendapatanlap_chart_main'),
      'access callback' => 'user_is_logged_in',
      'file' => 'pendapatanlap_chart_main.php',
      'type' => MENU_CALLBACK,
	  
    );
	

    return $items;
}


function pendapatanlap_title_callback() {
    return t('Anggaran per SKPD');
}

function pendapatanrek_title_callback() {
    return t('Anggaran per Rekening');
}

function pendapatanrekskpd_title_callback() {
    return t('Anggaran per Rekening');
}

 
function pendapatanlap_cron() {

}

