<?php
// $Id$

/**
 * Implementation of hook_perm().
 */
//onModuleCreationWizard
function belanja_perm() {
    return array(
        'access belanja content',
		'access laporan belanja'
	);
}

/**
 * Implementation of hook_menu().
 */

function belanja_menu() {


	$items['belanja'] = array (
      'title' => 'Belanja Kegiatan',
	  'description' => 'Belanja Kegiatan',
	  'title callback' => 'belanja_title_callback',	  
      'page callback' => 'belanja_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'belanja_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
	$items['belanja/rekening'] = array (
	  'title' => 'Rekening Belanja',
      'page callback' => 'belanja_edit_main',
      'page arguments' => array('belanja_edit_main'),
      'access callback' => 'user_is_logged_in',
      'file' => 'belanja_edit_main.php',
      'type' => MENU_CALLBACK,
	  
    );
	$items['belanja/jenis'] = array (
	  'title' => 'Jenis Belanja',
      'page callback' => 'belanja_jenis_main',
      'page arguments' => array('belanja_jenis_main'),
      'access callback' => 'user_is_logged_in',
      'file' => 'belanja_jenis_main.php',
      'type' => MENU_CALLBACK,
	  
    );
	$items['belanja/chart'] = array (
	  'title' => 'Grafis Belanja',
      'page callback' => 'belanja_chart_main',
      'page arguments' => array('belanja_chart_main'),
      'access callback' => 'user_is_logged_in',
      'file' => 'belanja_chart_main.php',
      'type' => MENU_CALLBACK,
	  
    );

	$items['belanjarek'] = array (
      'title' => 'Belanja per Rekening',
	  'description' => 'Belanja per Rekening',
	  'title callback' => 'belanjarek_title_callback',	  
      'page callback' => 'belanjarek_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'file' => 'belanjarek_main.php',
      'type' => MENU_NORMAL_ITEM,
    );	

	$items['belanjauk'] = array (
      'title' => 'Belanja per SKPD',
	  'description' => 'Belanja per SKPD',
	  'title callback' => 'belanjauk_title_callback',	  
      'page callback' => 'belanjauk_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'file' => 'belanjauk_main.php',
      'type' => MENU_NORMAL_ITEM,
    );	

	$items['belanjaurusan'] = array (
      'title' => 'Belanja per Urusan',
	  'description' => 'Belanja per Urusan',
	  'title callback' => 'belanjaurusan_title_callback',	  
      'page callback' => 'belanjaurusan_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'file' => 'belanjaurusan_main.php',
      'type' => MENU_NORMAL_ITEM,
    );	
	
	$items['belanjafungsi'] = array (
      'title' => 'Belanja per Fungsi',
	  'description' => 'Belanja per Fungsi',
	  'title callback' => 'belanjafungsi_title_callback',	  
      'page callback' => 'belanjafungsi_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'file' => 'belanjafungsi_main.php',
      'type' => MENU_NORMAL_ITEM,
    );	
	$items['belanjasumberdana'] = array (
      'title' => 'Belanja per Sumberdana',
	  'description' => 'Belanja per Sumberdana',
	  'title callback' => 'belanjasumberdana_title_callback',	  
      'page callback' => 'belanjasumberdana_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'file' => 'belanjasumberdana_main.php',
      'type' => MENU_NORMAL_ITEM,
    );	
	
	$items['belanjarek/skpd'] = array (
      'title' => 'Anggaran Belanja SKPD',
	  'description' => 'Anggaran Belanja SKPD',
	  'title callback' => 'belanjarek_title_callback',	  
      'page callback' => 'belanjarek_skpd_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'file' => 'belanjarek_skpd_main.php',
      'type' => MENU_NORMAL_ITEM,
    );	
	$items['belanjarek/kegiatan'] = array (
      'title' => 'Anggaran Belanja Kegiatan',
	  'description' => 'Anggaran Belanja Kegiatan',
	  'title callback' => 'belanjarek_title_callback',	  
      'page callback' => 'belanjarek_keg_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'file' => 'belanjarek_keg_main.php',
      'type' => MENU_NORMAL_ITEM,
    );	
    return $items;
}


function belanja_title_callback() {
    return t('Belanja Kegiatan');
}

function belanjarek_title_callback() {
    return t('Belanja per Rekening');
}

function belanjauk_title_callback() {
    return t('Belanja per SKPD');
}

function belanjaurusan_title_callback() {
    return t('Belanja per Urusan');
}
 
function belanjafungsi_title_callback() {
    return t('Belanja per Fungsi');
}

function belanjasumberdana_title_callback() {
    return t('Belanja per Sumberdana');
}

function belanja_cron() {

}

function arrayCopy( array $array ) {
        $result = array();
        foreach( $array as $key => $val ) {
            if( is_array( $val ) ) {
                $result[$key] = arrayCopy( $val );
            } elseif ( is_object( $val ) ) {
                $result[$key] = clone $val;
            } else {
                $result[$key] = $val;
            }
        }
        return $result;
}

?>
