<?php
// $Id$

/**
 * Implementation of hook_perm().
 */
//onModuleCreationWizard
function umumpusat_perm() {
    return array(
        'access penata content',
		'access laporan penata'
	);
}

/**
 * Implementation of hook_menu().
 */

function umumpusat_menu() {

	$items['umumpusat/antrian'] = array (
      'title' => 'Jurnal Umum | Pilih Pengembalian',
	  'description' => 'Jurnal Umum | Pilih Pengembalian',
	  //'title callback' => 'umum_title_callback',	  
      'page callback' => 'umumpusat_antrian_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'umumpusat_antrian_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
	
	//Kegiatan
	//1. select uk
	$items['umumpusat/selectuk'] = array (
      'title' => 'Jurnal Umum | Pilih SKPD',
	  'description' => 'Jurnal Umum | Pilih SKPD',
	  //'title callback' => 'umumpusat_title_callback',	  
      'page callback' => 'umumpusatkeg_selectuk_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'umumpusatkeg_selectuk_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
	//2. select keg
	$items['umumpusat/newpick'] = array (
      'title' => 'Jurnal Umum | Pilih Kegiatan',
	  'description' => 'Jurnal Umum | Pilih Kegiatan',
	  //'title callback' => 'umumpusat_title_callback',	  
      'page callback' => 'umumpusatkeg_newpick_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'umumpusatkeg_newpick_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
	//3. posting keg
	$items['umumpusat/newpost'] = array (
      'title' => 'Jurnal Umum',
	  'description' => 'Jurnal Umum',
	  //'title callback' => 'umumpusat_title_callback',	  
      'page callback' => 'umumpusatkeg_newpost_main',
      //'access arguments' => array ('access content'), 
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'umumpusatkeg_newpost_main.php',
      'type' => MENU_NORMAL_ITEM,
    );	
	
	//KAS
	$items['umumpusat/jurnalkas'] = array (
      'title' => 'Jurnal Umum | Pengembalian Kas',
	  'description' => 'Jurnal Umum | Pengembalian Kas',
	  //'title callback' => 'jurnalspjjurnal_title_callback',	  
      'page callback' => 'umumpusat_newkas_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'umumpusat_newkas_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
	$items['umumpusat/jurnalpad'] = array (
      'title' => 'Jurnal Umum | Pendapatan',
	  'description' => 'Jurnal Umum | Pendapatan',
	  //'title callback' => 'jurnalspjjurnal_title_callback',	  
      'page callback' => 'umumpusat_newpad_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'umumpusat_newpad_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
	
    return $items;
}


function umumpusat_title_callback() {
    return t('Jurnal Umum');
}


