<?php
// $Id$

/**
 * Implementation of hook_perm().
 */
//onModuleCreationWizard
function persediaan_perm() {
    return array(
        'access penata content',
		'access laporan penata'
	);
}

/**
 * Implementation of hook_menu().
 */

function persediaan_menu() {

	$items['persediaan'] = array (
      'title' => 'Antrian Jurnal Persediaan',
	  'description' => 'Antrian Jurnal Persediaan',
	  'title callback' => 'persediaan_title_callback',	  
      'page callback' => 'persediaan_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'persediaan_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
	$items['persediaan/jurnal'] = array (
      'title' => 'Jurnal Persediaan',
	  'description' => 'Jurnal Persediaan',
	  'title callback' => 'persediaan_title_callback',	  
      'page callback' => 'persediaan_edit_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'persediaan_edit_main.php',
      'type' => MENU_NORMAL_ITEM,
    );

	

    return $items;
}


function persediaan_title_callback() {
    return t('Jurnal Persediaan');
}


