<?php
function jurnal_perm() {
    return array(
        'access jurnal content',
		'access laporan jurnal'
	);
}

/**
 * Implementation of hook_menu().
 */

function jurnal_menu() {

	$items['jurnal'] = array (
      'title' => 'Anggaran jurnal',
	  'description' => 'Anggaran jurnal',
	  'title callback' => 'jurnal_title_callback',	  
      'page callback' => 'jurnal_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'jurnal_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
	$items['jurnal/edit'] = array (
      'title' => 'Anggaran jurnal usahaan SKPD',
	  'description' => 'Anggaran jurnal usahaan',
	  'title callback' => 'jurnal_title_callback',	  
      'page callback' => 'jurnal_edit_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'jurnal_edit_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
	

    return $items;
}


function jurnal_title_callback() {
    return t('jurnalusahaan');
}


function jurnal_block_info() {
  // Many options are defined in hook_block_info():
  $blocks['register_sp2d_kegiatan'] = array(
    // info: The name of the block.
    'info' => t('Register SP2D Kegiatan'),
    // Block caching options (per role, per user, etc.)
    // DRUPAL_CACHE_PER_ROLE is the default.
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );

  /*
  // This sample shows how to provide default settings. In this case we'll
  // enable the block in the first sidebar and make it visible only on
  // 'node/*' pages. See the hook_block_info() documentation for these.
  $blocks['example_empty'] = array(
    'info' => t('Example: empty block'),
    'status' => TRUE,
    'region' => 'sidebar_first',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'node/*',
  );
  */

  return $blocks;
}